/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Simple TODO API
 * A simple API to manage TODO tasks.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from '../schemas-user/user';

export type UserList = User[];
