/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Simple TODO API
 * A simple API to manage TODO tasks.
 * OpenAPI spec version: 1.0.0
 */

export interface Todo {
  /** The unique identifier for a TODO */
  id?: string;
  /** The title of the TODO */
  title?: string;
  /** Whether the TODO is completed */
  completed?: boolean;
}
