/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Simple TODO API
 * A simple API to manage TODO tasks.
 * OpenAPI spec version: 1.0.0
 */
import type { Todo } from '../schemas-todo/todo';

export type TodoList = Todo[];
