/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Simple TODO API
 * A simple API to manage TODO tasks.
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  /** The unique identifier for a user */
  id?: string;
  /** The name of the user */
  name?: string;
  /** The email address of the user */
  email?: string;
}
